export const mockData = [
  {
    listName: "My Grocery List",
    date: "02/13/2022",
    list: [
      {
        id: "wefew23rfef324",
        listItemName: "Carrots",
        listItemCategory: "Produce",
        listItemQuantity: "4",
        isChecked: true,
      },
      {
        id: "wefew23rfef3333",
        listItemName: "Onion",
        listItemCategory: "Produce",
        listItemQuantity: "1",
        isChecked: true,
      },
      {
        id: "wefew23rfef3123",
        listItemName: "Celery",
        listItemCategory: "Produce",
        listItemQuantity: "6",
        isChecked: true,
      },
      {
        id: "wpoij62356324",
        listItemName: "Steak",
        listItemCategory: "Meat",
        listItemQuantity: "2",
        isChecked: false,
      },
      {
        id: "oei2fj320978tuf",
        listItemName: "Bacon",
        listItemCategory: "Meat",
        listItemQuantity: "1",
        isChecked: false,
      },
      {
        id: "oei2fj32097844",
        listItemName: "Shrimp",
        listItemCategory: "Meat",
        listItemQuantity: "3",
        isChecked: false,
      },
      {
        id: "oei2fj3209784222",
        listItemName: "Ground Beef",
        listItemCategory: "Meat",
        listItemQuantity: "3",
        isChecked: false,
      },
      {
        id: "oei2fj35432",
        listItemName: "Chicken",
        listItemCategory: "Meat",
        listItemQuantity: "3",
        isChecked: false,
      },
      {
        id: "wefew23rfef3241",
        listItemName: "Carrots",
        listItemCategory: "Produce",
        listItemQuantity: "4",
        isChecked: true,
      },
      {
        id: "wefew23rfef33331",
        listItemName: "Onion",
        listItemCategory: "Produce",
        listItemQuantity: "1",
        isChecked: true,
      },
      {
        id: "wefew23rfef31231",
        listItemName: "Celery",
        listItemCategory: "Produce",
        listItemQuantity: "6",
        isChecked: true,
      },
      {
        id: "wpoij623563241",
        listItemName: "Steak",
        listItemCategory: "Meat",
        listItemQuantity: "2",
        isChecked: false,
      },
      {
        id: "oei2fj320978tu1f",
        listItemName: "Bacon",
        listItemCategory: "Meat",
        listItemQuantity: "1",
        isChecked: false,
      },
      {
        id: "oei2fj320978144",
        listItemName: "Shrimp",
        listItemCategory: "Meat",
        listItemQuantity: "3",
        isChecked: false,
      },
      {
        id: "oei2fj32097814222",
        listItemName: "Ground Beef",
        listItemCategory: "Meat",
        listItemQuantity: "3",
        isChecked: false,
      },
      {
        id: "oei2fj354132",
        listItemName: "Chicken",
        listItemCategory: "Meat",
        listItemQuantity: "3",
        isChecked: false,
      },
    ],
  },
];
